---
title: "introBayes"
author: "jmm"
date: "September 10, 2015"
output: html_document
---

# Análisis Bayesiano

Los análisis Bayesianos son similares a los que vimos en [máxima verosimilitud](http://rpubs.com/pajaro/mle) en el sentido que dependen explícitamente de modelos probabilísticos. Pero la gran diferencia es que con Bayes, usamos las reglas de probabilidades para llegar a distribuciones de probabilidades para todas las cantidades no observadas, incluyendo parámetros, valores perdidos o nuevas observaciones. De esta manera, los análisis Bayesianos nos permiten **cuantificar incertidumbre**. 

Como veremos más adelante, los análisis Bayesianos combinados con métodos numéricos permiten analizar modelos con muchos parámetros y niveles de variabilidad pero primero vamos a empezar por casos simples donde podemos calcular las posteriores directamente. 

En algunos casos es posible obtener expresiones a


# leer datos
quintral <- read.table("http://modelosydatos.googlepages.com/quintral.txt", header = T)

# Son datos de remociÛn de frutos de sitios pareados con bosque continuo y fragmentado 
View(quintral)
attach(quintral)

# Asumimos una distribucion Binomial para los datos, y podemos usar su previa conjudada que es la distribuciÛn Beta

# Par·metros previos 
alpha = 1;
beta = 1;
# Estas previas corresponden a una distribuciÛn uniforme entre 0 y 1, por lo tanto es una previa "no informativa" Û "vague" 

#graficamos la previa
x = seq(from = 0, to = 1, by = 0.01) 
plot(x, dbeta(x, alpha,beta), type = "l", xlab = expression(paste("value of ", theta)), ylab = "Probability Density")

# para una sola observaciÛn: 
pos_theta1 = dbeta(x, alpha + sum(Removidos[1]) , beta + sum((Frutos[1]-Removidos[1])))

# Dado que la Beta es la conjugada de la Binomial, la posterior es otra Beta, con los par·metros actualizados con los datos. 

#En este caso la nueva "alpha" es igual al alpha previo m·s el n˙mero total de "Èxitos" en los datos (Binomial) mientras que "beta" es igual al beta previo m·s el n˙mero total de "fracasos" en los datos

plot(x,pos_theta1, type = "l",lwd=2,col="gray", xlab = expression(paste("value of ", theta)), ylab = "Probability Density")
lines(x, dbeta(x,alpha,beta))
lines(c(Removidos[1]/Frutos[1],Removidos[1]/Frutos[1]),c(0,6))
text(0.75,5,"posterior",col="darkgray",adj=0)
text(0.55,5.5, "data")
text(0.1,1.5,"prior")

# øQuÈ pasa si incluimos m·s observaciones?
plot(x,dbeta(x, alpha + sum(Removidos[1:10]) , beta + sum((Frutos[1:10]-Removidos[1:10]))), type = "l", xlab = expression(paste("value of ", theta)), lwd=2,col="gray", ylab = "Probability Density")
lines(x, dbeta(x,alpha,beta))
text(0.75,15,"posterior",col="darkgray",adj=0)
text(0.1,2.5,"prior")

# Ahora con todos los datos
pos_theta1 = dbeta(x, alpha + sum(Removidos) , beta + sum((Frutos-Removidos)))

plot(x,pos_theta1, type="l", xlab = expression(paste("value of ", theta)), lwd=2,col="gray", ylab = "Probability Density")
lines(x, dbeta(x,alpha,beta))
text(0.65,35,"posterior",col="darkgray",adj=0)
text(0.1,5,"prior")

# Podemos usar pbeta, qbeta para responder preguntas acerca de la posterior 
# "tcredint" en el paquete emdbook de Bolker calcula los intervalos de credibilidad 

# La probabilidad de que la remociÛn de frutos sea <= 0.5 es
pbeta(0.5, alpha+sum(Removidos),beta+sum((Frutos-Removidos)))

# El intervalo del 95% para la probabilidad de remociÛn de frutos es 
qbeta(c(0.025,0.975),alpha+sum(Removidos),beta+sum((Frutos-Removidos)))

library(emdbook)   #para hacer el intervalo de credibilidad con la funcion tcredint()
tcredint("beta",list(shape1= alpha+sum(Removidos), shape2 = beta+sum((Frutos-Removidos))),verbose=T)
# El intervalo de credibilidad del 95% es apenas diferente:


####################################################

# Las observaciones vienen de sitios diferentes 

x = seq(from = 0, to = 1, by = 0.0001)
plot(x,dbeta(x,alpha+sum(Removidos),beta+sum(Frutos-Removidos)), type = "l", lwd=2,col="darkgrey", xlab = expression(paste("Fruit Removal Probability ", (theta) ),ylab = "Posterior", xlim=c(0.3,0.9), ylim=c(0,45)))
co = which(bosque=="c")  #bosque continuo
fr = which(bosque=="f")  #bosque fragmentado
lines(x,dbeta(x,alpha + sum(Removidos[co]), beta+sum((Frutos[co]-Removidos[co]))),lwd=2)
lines(x,dbeta(x,alpha + sum(Removidos[fr]), beta+sum((Frutos[fr]-Removidos[fr]))),lwd=2)
text(0.4,30,"fragments")
text(0.8,38,"continuous forest")
text(0.6,45,"all")

# Discriminamos por sitio y fragmentos de bosque. Hay fragmentos y bosque continuo en varios sitios diferentes
x = seq(from = 0, to = 1, by = 0.0001)

op=par(lwd=2, cex.lab=1.3)
plot(x,dbeta(x,alpha+sum(Removidos),beta+sum(Frutos-Removidos)), type = "l",col="darkgrey", xlab = expression(paste("Fruit Removal Probability ", (theta))),ylab = "Posterior Probability Density", xlim=c(0.2,0.9), ylim=c(0,45))
coc = which(bosque=="c" & sitio == "Campanario")
cot = which(bosque=="c" & sitio == "Tacul")
coll = which(bosque=="c" & sitio == "Llao-Llao")
frc = which(bosque=="f" & sitio == "Campanario")
frt = which(bosque=="f" & sitio == "Tacul")
frll = which(bosque=="f" & sitio == "Llao-Llao")

lines(x,dbeta(x,alpha + sum(Removidos[coc]), beta+sum((Frutos[coc]-Removidos[coc]))), col="blue")
lines(x,dbeta(x,alpha + sum(Removidos[cot]), beta+sum((Frutos[cot]-Removidos[cot]))), col="red")
lines(x,dbeta(x,alpha + sum(Removidos[coll]), beta+sum((Frutos[coll]-Removidos[coll]))), col = "magenta")
lines(x,dbeta(x,alpha + sum(Removidos[frc]), beta+sum((Frutos[frc]-Removidos[frc]))), col="blue")
lines(x,dbeta(x,alpha + sum(Removidos[frt]), beta+sum((Frutos[frt]-Removidos[frt]))), col="red")
lines(x,dbeta(x,alpha + sum(Removidos[frll]), beta+sum((Frutos[frll]-Removidos[frll]))),col="magenta")

text(0.4,25,"Fragments", cex=1.2)
text(0.8,28,"Continuos Forests", cex=1.2)
text(0.6,45,"Pooled Data", cex=1.2)
legend(0.27,40,c("Campanario", "Tacul", "Llao Llao"), lty = c(1,1,1), lwd = c(2,2,2), col=c("blue","red","magenta"), cex=1.2)
#text(0.27,40,"Campanario",col="blue")
#text(0.27,38,"Tacul",col="red")
#text(0.27,36,"Llao Llao", col="magenta")
par(op)

#-------------------------------------------------------------------------------
# Calcular los intervalos de credibilidad para la remociÛn de frutos en todos los sitios y fragmentos 

